ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
ENV['VAGRANT_PROJECT_ROOT'] = File.dirname(__FILE__)

NODES = {
  "k3s-server"   => { :ip => "192.168.100.10", :cpus => 1, :mem => 1536 },
  "k3s-agent-1" => { :ip => "192.168.100.11", :cpus => 1, :mem => 1024 },
  "k3s-agent-2" => { :ip => "192.168.100.12", :cpus => 1, :mem => 1024 }
}

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |kvm|
    kvm.management_network_name = "vagrant-libvirt"
  end

  NODES.each do |node_name, node_meta|
    config.vm.define node_name do |node|
      node.vm.hostname = node_name

      node.vm.network "private_network",
        ip: node_meta[:ip],
        netmask: "255.255.255.0",
        libvirt__dhcp_enabled: false

      node.vm.provider :libvirt do |kvm|
        kvm.cpus = node_meta[:cpus]
        kvm.memory = node_meta[:mem]
      end

      # 1. Run network optimization patch pointing to your scripts folder
      node.vm.provision "shell", path: "scripts/sysctl-networking.sh"

      # 2. Run the specific K3s installation scripts from the subfolder
      if node_name == "k3s-server"
        node.vm.provision "shell", path: "scripts/k3s-server.sh"
      else
        node.vm.provision "shell", path: "scripts/k3s-agent.sh", args: [node_name, node_meta[:ip]]
      end
    end
  end
end