apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.100.200-192.168.100.220 # ◄── Dedicated safe range for your cluster services
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lab-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - lab-ip-pool